apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: microservices
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service.microservices.svc.cluster.local:8000']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service.microservices.svc.cluster.local:8001']

